global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'book-logger-azure'
    static_configs:
      - targets: ['book-logger-backend.greendune-dcdd87fc.westeurope.azurecontainerapps.io:443']
    metrics_path: '/metrics'
    scheme: 'https'
  
  # Local development target (when running locally)
  - job_name: 'book-logger-local'
    static_configs:
      - targets: ['host.docker.internal:5001']
    metrics_path: '/metrics'

